[package]
name = "burnlm-registry"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ["tracel-plugins"]

tracel-plugins = [
"burnlm-inference-llama3",
"burnlm-inference-tinyllama",
]

community-plugins = []

[dependencies]
burnlm-inference = { path = "../burnlm-inference" }
burnlm-inference-llama3 = { path = "../burnlm-inference-llama3", optional = true }
burnlm-inference-tinyllama = { path = "../burnlm-inference-tinyllama", optional = true }
burn = { workspace = true }
