[package]
name = "burnlm-registry"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[lib]
name = "burnlm_registry"
crate-type = ["dylib"]

[features]
default = ["tracel-plugins"]

tracel-plugins = [
"burnlm-plugin-llama3",
"burnlm-plugin-tinyllama",
]

community-plugins = []

[dependencies]
burnlm-inference = { path = "../burnlm-inference" }
burnlm-plugin-llama3 = { path = "../burnlm-plugin-llama3", optional = true }
burnlm-plugin-tinyllama = { path = "../burnlm-plugin-tinyllama", optional = true }
burn = { workspace = true }
