[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/burnlm-cli",
    "crates/burnlm-http",
    "crates/burnlm-inference",
    "crates/burnlm-macros",
    "crates/burnlm-plugin-tinyllama",
    "crates/burnlm-plugin-llama3",
    "crates/burnlm-registry",
    "models/llama-burn",
    "xtask",
]

[workspace.package]
edition = "2021"
version = "0.0.1"
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace.dependencies]
burn = { version = "0.14.0", default-features = false, features = ["std"] }

anyhow = "1.0.95"
axum = { version = "0.7.9", features = ["macros"] }
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.22", features = ["derive", "cargo"] }
dirs = { version = "5.0.1" }
dotenvy = "0.15.7"
gensym = "0.1.1"
inventory = "0.3.17"
lazy_static = "1.5.0"
log = "0.4.22"
once_cell = "1.20.2"
paste = "1.0.15"
proc-macro2 = "1.0.93"
quote = "1.0.38"
rand = "0.8.5"
rstest = "0.2.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
strum = { version = "0.26.3", features = ["derive"] }
syn = { version = "2.0.96", features = ["full"] }
thiserror = "2"
tokio = { version = "1.42.0", features = ["full"] }
tokio-stream = "0.1.17"
tower-http = { version = "0.6.0", features = [
    "fs",
    "cors",
    "trace",
    "request-id",
] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = {version = "0.3.19", features = ["env-filter", "registry"]}
utoipa = { version = "5.2.0", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "8.0.3", features = ["axum"] }

# models
base64 = { version = "0.22.1" }
rustc-hash = { version = "1.1.0" }
tiktoken-rs = { version = "0.5.8" }
tokenizers = { version = "0.19.1", default-features = false, features = ["onig"] }

### For xtask crate ###
tracel-xtask = { version = "=1.1.8" }

[profile.dev]
debug = 0 # Speed up compilation time and not necessary.
opt-level = 0
incremental = false # needed for inventory crate to actually do its job (https://github.com/dtolnay/inventory/issues/24)
