[profiling]
logger = { file = "/tmp/profiling.log", level = "medium" }

[autotune]
logger = { file = "/tmp/autotune.log", level = "minimal" }

[compilation]
logger = { file = "/tmp/compilation.log", level = "disabled" }
# cache = "target"
