[profiling]
logger = { file = "/tmp/profiling.log", level = "disabled" }

[autotune]
logger = { file = "/tmp/autotune.log", level = "disabled" }

[compilation]
logger = { file = "/tmp/compilation.log", level = "disabled" }
cache = "target"
