[profiling]
logger = { file = "/tmp/profiling.log", level = "minimal" }

[autotune]
logger = { file = "/tmp/autotune.log", level = "minimal" }

[compilation]
logger = { file = "/tmp/compilation.log", level = "basic" }
cache = "target"
