[package]
name = "burnlm-inference"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[features]
# Don't define a default feature ! Keep this commented
# We use a build script to set the default feature to make sure that
# only one backend feature is enabled.
# using --no-default-features does not cut it here because we always need
# at least one and only one backend feature set.
# default = []

candle-accelerate = ["burn/candle", "burn/accelerate"]
candle-cpu = ["burn/candle"]
candle-cuda = ["burn/candle-cuda"]
candle-metal = ["burn/candle", "burn/metal"]
cuda = ["burn/cuda", "burn/fusion"]
rocm = ["burn/rocm"]
libtorch = ["burn/tch"]
libtorch-cpu = ["burn/tch"]
ndarray = ["burn/ndarray"]
ndarray-blas-accelerate = ["burn/ndarray", "burn/accelerate"]
ndarray-blas-netlib = ["burn/ndarray", "burn/blas-netlib"]
ndarray-blas-openblas = ["burn/ndarray", "burn/openblas"]
wgpu = ["burn/wgpu", "burn/autotune"]
vulkan = ["burn/vulkan", "burn/autotune", "burn/fusion"]
wgpu-cpu = ["burn/wgpu", "burn/autotune", "burn/fusion"]

[dependencies]
burn = { workspace = true, features = ["wgpu", "autotune"] }
llama-burn = { path = "../../models/llama-burn" }
burnlm-macros = { path = "../burnlm-macros" }

clap = { workspace = true }
comfy-table = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }