[alias]
xtask = "run --target-dir target/xtask --package xtask --bin xtask --"
# we don't build in release because we want burnlm launcher to build as fast as possible
burnlm = "run --bin burn-lm --profile launcher --"
bb = "run --release --bin burnbench --"
