[package]
name = "burnlm-cli"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
burnlm-inference = { path = "../burnlm-inference" }
burnlm-registry = { path = "../burnlm-registry" }

anyhow = { workspace = true }
clap = { workspace = true }

[[bin]]
name = "burnlm"
path = "src/bin/burnlm.rs"
