procs:
  open-webui:
    shell: 'docker "logs" "-f" "open-webui"'
    autostart: true
    autorestart: true
    stop: SIGTERM
  openai-server:
    shell: 'cargo burn-lm -b {{BACKEND}} -d {{DTYPE}} server run --port 3001'
    autostart: true
    autorestart: true
    stop: {send-keys: ["<C-c>"]}
